[tox]
requires =
    tox>=4.2
env_list =
    py{313, 312, 311}

[testenv]
runner = uv-venv-runner
deps =
    aa-contacts
    aa-market-manager
    aa-memberaudit
    aa-miningtaxes
    aa-moonmining
    aa-structures
    allianceauth-afat
    allianceauth-app-utils
    allianceauth-corptools
    allianceauth-securegroups
    coverage
    django-eveonline-sde
    django-eveuniverse
    factory_boy
pass_env =
    AA_DB_HOST
    AA_DB_NAME
    AA_DB_PASSWORD
    AA_DB_PORT
    AA_DB_USER
    AA_REDIS
    USE_MYSQL
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    coverage run runtests.py charlink -v 2
    coverage report
    coverage xml

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
