name: Checks

on:
  push:
    paths-ignore:
      - "**.css"
      - "**.js"
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.css"
      - "**.js"
      - "**.md"

jobs:
  build-test:
    name: PyPi Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          check-latest: true

      - name: Install Tools
        run: |
          python -m pip install -U pip
          pip install -U build
      - name: Package Build
        env:
          STACKMANAGER_VERSION: 9999
        run: python -m build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          if-no-files-found: ignore
